name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  URL: https://git.liteyuki.org
  OWNER: liteyuki-docker
  REPO: neo-blog

jobs:
  gitea-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Gitea Deploy Workflow
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
            "${{ env.URL }}/api/v1/repos/${{ env.OWNER }}/${{ env.REPO }}/mirror-sync" \
            -d '{"branch": "main"}'